//#define STB_CONNECTED_COMPONENTS_IMPLEMENTATION
//#define STB_C_LEXER_IMPLEMENTATION
//#define STB_DIVIDE_IMPLEMENTATION
//#define STB_DS_IMPLEMENTATION
//#define STB_DXT_IMPLEMENTATION
//#define STB_HBWANG_STATIC
//#define STB_HEXWAVE_STATIC
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_RESIZE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
//#define STB_INCLUDE_IMPLEMENTATION
#define STB_LEAKCHECK_IMPLEMENTATION
//#define STB_PERLIN_IMPLEMENTATION
//#define STBRP_STATIC
//#define STB_SPRINTF_IMPLEMENTATION
//#define STB_TEXTEDIT_IMPLEMENTATION
//#define STB_TILEMAP_EDITOR_IMPLEMENTATION
//#define STB_TRUETYPE_IMPLEMENTATION
//#define STB_VOXEL_RENDER_STATIC

//#define STBCC_GRID_COUNT_X_LOG2
//#define STBCC_GRID_COUNT_Y_LOG2
//#define STBCC_CLUSTER_SIZE_X_LOG2
//#define STBCC_CLUSTER_SIZE_Y_LOG2

#include <FeatherCommon.h>